### ISSUE TITLE
Add the ability to configure the QuickSup Icon 

### ISSUE THREAD

**Issue by WaleedAlrashed** [maestralsol/sup#1]
Both `QuickSup.empty()` and` QuickSup.error()` constructors give **predefined icon widgets** for their respective cases (which is fine).
But Sometimes, we may need to provide a custom Widget (`Icon`, `SvgAsset `..) to match the overall design of the app.
Even though we can use the Sup() constructor to achieve that. but then we have to provide other widgets according to each use case.

Is this something you may consider doing?

Side note: this package is one of the most important and amazing packages in the pub.dev, Appreciate your hard work

**Comment by xiprox** [comment]
Hey! As exaggerated as they may be, thanks for the kind words. :)

This is definitely something I'd like to do. Can't give you any estimates though.

In the meantime, if you (or anyone else) would like to try your hand at implementing this, I'd gladly welcome a PR (and would help if necessary). I'm thinking there'd probably be a Widget param for the image, and perhaps a bool param like `wrapImageInCircle`, which would default to true, so that if you passed something simple like `Icon(Icons.warning)`, you'd be able to make use of the default style, but if you preferred to use a more custom image, you'd be able to get rid of the circle.

**Comment by xiprox** [comment]
This has been implemented and is now live on pub with v1.1.0.
